name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    if: github.repository == 'dusk-network/duskit'
    permissions:
      contents: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting up Node 22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
          scope: "@duskit"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "Version packages"
          publish: npm run release
          title: "Version packages"
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
